### ISSUE TITLE
New repository for oemof examples

### ISSUE THREAD

**Issue by birgits** [oemof/oemof_examples#1]
In the webco we said that it would be a good idea to have a repository to collect all kinds of examples and jupyter notebooks from us and people who want to contribute and add a note to the documentation and homepage that input is welcome. If anyone disagrees please say so!

**Comment by birgits** [comment]
Since there haven't been any objections about this repo so far, who wants to contribute their example?

**Comment by birgits** [comment]
I added my sector coupling notebook from the user meeting as a first example and am hoping that we will start to use this repo. We should at some point decide about minimum criteria the examples should meet. I am also open for suggestions if you think the repo should be structured differently.

**Comment by uvchik** [comment]
I like the example. If you like you could make an announcement on the webpage.

You could connect it with the call to add examples.

**Comment by ckaldemeyer** [comment]
> I added my sector coupling notebook from the user meeting as a first example and am hoping that we will start to use this repo. We should at some point decide about minimum criteria the examples should meet. I am also open for suggestions if you think the repo should be structured differently.

Did we agree that all examples are being moved to this one or do both exist in parallel?

Thanks for your effort!

**Comment by c-moeller** [comment]
I added my example. It's not as nice as birgits' one and there is only one parameter variation until now (in the workshop we had four), but I'm going to improve it, also with a possible oemof tutorial in mind.

> Did we agree that all examples are being moved to this one or do both exist in parallel?

What is the other one?

**Comment by ckaldemeyer** [comment]
> I added my example. It's not as nice as birgits' one and there is only one parameter variation until now (in the workshop we had four), but I'm going to improve it, also with a possible oemof tutorial in mind.
> 
> Did we agree that all examples are being moved to this one or do both exist in parallel?
> What is the other one?

The original repository: https://github.com/oemof/oemof/tree/dev/examples

**Comment by c-moeller** [comment]
> The original repository: https://github.com/oemof/oemof/tree/dev/examples

Ah ok... maybe we should only collect jupyter notebooks here to have a more interactive way of presenting our examples (and keep the examples as python files in the oemof repository). Just an idea.

**Comment by birgits** [comment]
Maybe the examples in the oemof/oemof repo could be more basic examples mainly focusing on showing functionalities of packages inside the repo while examples in the examples repo can be more elaborate and include other oemof libraries? I wouldn't limit it to jupyter notebooks.

**Comment by ckaldemeyer** [comment]
> Maybe the examples in the oemof/oemof repo could be more basic examples mainly focusing on showing functionalities of packages inside the repo while examples in the examples repo can be more elaborate and include other oemof libraries? I wouldn't limit it to jupyter notebooks.

I would agree. And maybe the ones in the oemof/oemof repo could be adjusted to be very simple and intuitive and organized in the same (minimalistic) structure. From my point of view some of the examples are quite overloaded due to historical reasons :-)

**Comment by uvchik** [comment]
@birgits Thank you for the post on the webpage.

I'm fine with copying the examples to the examples repository. For me it is no problem that they are duplicate because we do not have to keep them in line. 

Touching the examples in oemof/oemof might be more work than it seems to be on the first glance, because there are various links in the documentation and script that make these examples executable. Furthermore we use the examples for testing purpose.

**Comment by birgits** [comment]
> I'm fine with copying the examples to the examples repository. For me it is no problem that they are duplicate because we do not have to keep them in line.

If no one has any objections against @uvchik's suggestion I would copy the examples to the this repo. My only concern is that we'd have to maintain the same example in two repos.

**Comment by ckaldemeyer** [comment]
> I'm fine with copying the examples to the examples repository. For me it is no problem that they are duplicate because we do not have to keep them in line.
> If no one has any objections against @uvchik's suggestion I would copy the examples to the this repo. My only concern is that we'd have to maintain the same example in two repos.

Maybe we can then simplify some of them in the second stage.

So `oemof/examples` could be mainly for illustrative purposes holding minimalistic examples and `oemof/oemof` holds the more extensive examples for testing, etc.

What do you think?

**Comment by uvchik** [comment]
> So oemof/examples could be mainly for illustrative purposes holding minimalistic examples and oemof/oemof holds the more extensive examples for testing, etc.

I agree. First of all these examples are already pretty good and as @ckaldemeyer said, we will develop them in different ways.

Then we should change the oemof documentation and link to the example repository. I think a list of all examples and a short description (1-3 sentences) in the README of the examples repository what be enough.

In this context the oemof examples will become developer examples as @ckaldemeyer described above.

We still have the example-script that @gplssm wrote. In my opinion we should change it to a testing script. So that people can execute the script and get messages what works and what will not. For example cbc works, glpk not, plotting will not work because of missing matplotlib and so on. I could do this for the next major release.

**Comment by ckaldemeyer** [comment]
> So oemof/examples could be mainly for illustrative purposes holding minimalistic examples and oemof/oemof holds the more extensive examples for testing, etc.
> I agree. First of all these examples are already pretty good and as @ckaldemeyer said, we will develop them in different ways.
> 
> Then we should change the oemof documentation and link to the example repository. I think a list of all examples and a short description (1-3 sentences) in the README of the examples repository would be enough.
> 
> In this context the oemof examples will become developer examples as @ckaldemeyer described above.
> 
> We still have the example-script that @gplssm wrote. In my opinion we should change it to a testing script. So that people can execute the script and get messages what works and what will not. For example cbc works, glpk not, plotting will not work because of missing matplotlib and so on. I could do this for the next major release.

Should we then just rename `oemof/examples` into `oemof/testing` or something similar?

Then potential users would not assume working illustrative examples in this place which are now all in `oemof/examples`. Just as an idea to be explicit and self-explaining here..

**Comment by ckaldemeyer** [comment]
I corrected my post by the right repo name..

**Comment by uvchik** [comment]
Let's talk to @gnn about the names. The `testing_examples` are no real tests and we already have a `tests` folder in oemof/oemof. Maybe 'testing_examples', 'internal_examples' ... Would be interested what @gnn thinks about that.

**Comment by uvchik** [comment]
1. We do not have any examples within the oemof repository. All examples were moved here.
2. The example test were integrated into the unit test environment (see oemof/oemof#359)

I think we can close this issue.
