### ISSUE TITLE
Maximum capacity to infinity issue

### ISSUE THREAD

**Issue by DevMallaThakuri** [oemof/oemof_examples#83]
Hi folks, here I  have given the maximum value of the power plant a very high number- where I want to say the potential is infinity for heat pump and electric boiler. Is that correct? and how do I say the current installed capacity is zero?
Thanks in advance for any input.

**Comment by robbiemorrison** [comment]
Hi Dev, you can set your code in three back ticks to make it more readable:

- https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

Best too to specify "python" to improve the syntax highlighting. HTH,&nbsp;R.

**Comment by p-snft** [comment]
This is a cross-post from [the openmod forum](https://forum.openmod.org/t/please-help-my-simple-model-to-run/3509). As I think this is more of a forum topic then an issue with oemof-examples, I'll close this one in favour of a discussion at openmod.
